services:
  nginx:
    image: nginx
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - TZ=Asia/Dhaka
    depends_on: 
      - php-fpm
    networks:
      - preparation


  php-fpm:
    build: 
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini:rw
      - ./docker/php-fpm/openssl.cnf:/etc/ssl/openssl.cnf:rw
    environment:
      - APP_ENV="local"
      - APP_DEBUG="true"
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD} 
    depends_on: 
      - db
    networks:
      - preparation
  db:
    image: mysql:8
    ports:
      - "3310:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        MYSQL_DATABASE: "${DB_DATABASE}"
        MYSQL_USER: "${DB_USERNAME}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
     
    networks:
      - preparation

  redis:
    image: redis:latest
    ports: 
      - 6380:6379
    networks:
      - preparation

   
networks:
  preparation:

volumes:
  db_data: